import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plane, Globe } from 'lucide-react';
import { ItineraryForm } from './components/ItineraryForm';
import { ItineraryDisplay } from './components/ItineraryDisplay';
import { LoadingState } from './components/LoadingState';
import { generateItinerary } from './services/openai';
import type { TripFormData, Itinerary } from './types/itinerary';

function App() {
  const [itinerary, setItinerary] = useState<Itinerary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (form: TripFormData) => {
    setError('');
    setLoading(true);
    setItinerary(null);

    try {
      const result = await generateItinerary(form);
      setItinerary(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    setItinerary(null);
    setError('');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-sky-50/30 to-teal-50/20">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-lg border-b border-gray-100 sticky top-0 z-40">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="bg-gradient-to-br from-sky-500 to-teal-500 p-2 rounded-xl shadow-md">
              <Plane className="h-5 w-5 text-white" />
            </div>
            <span className="text-lg font-bold text-gray-900">TripCraft</span>
          </div>
          <div className="flex items-center gap-1.5 text-gray-400 text-sm">
            <Globe className="h-4 w-4" />
            <span className="hidden sm:inline">AI-Powered Travel Planning</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <AnimatePresence mode="wait">
          {!itinerary && !loading && (
            <motion.div
              key="form"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
            >
              {/* Hero text */}
              <div className="text-center mb-10">
                <motion.h1
                  className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                >
                  Where to next?
                </motion.h1>
                <motion.p
                  className="text-gray-500 text-base sm:text-lg max-w-md mx-auto"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.2 }}
                >
                  Get a detailed, personalized travel itinerary generated by AI in seconds.
                </motion.p>
              </div>

              <ItineraryForm onSubmit={handleSubmit} loading={loading} />

              {/* Error */}
              <AnimatePresence>
                {error && (
                  <motion.div
                    className="max-w-2xl mx-auto mt-6 bg-red-50 border border-red-200 text-red-700 px-5 py-4 rounded-xl text-sm"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0 }}
                  >
                    {error}
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}

          {loading && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <LoadingState />
            </motion.div>
          )}

          {itinerary && !loading && (
            <motion.div
              key="result"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.4 }}
            >
              <ItineraryDisplay itinerary={itinerary} onBack={handleBack} />
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 mt-16 py-6 text-center text-xs text-gray-400">
        Built with React, TailwindCSS, and OpenAI
      </footer>
    </div>
  );
}

export default App;
